---
all:
  vars:
    ansible_user: bourdonf
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_port: 22
    # Définir d'autres variables communes si nécessaire

prod:
  children:
    web:
      hosts:
        FB-WEB-PROD:
          ansible_host: 192.168.1.28
    bdd:
      hosts:
        FB-DB-PROD:
          ansible_host: 192.168.1.29
      vars:
        # Variables spécifiques aux bases de données

test:
  hosts:
    FB-QUAL:
      ansible_host: 192.168.1.30
  vars:
    # Variables spécifiques à l'environnement de test