---
all:
  vars:
    ansible_user: bourdonf
    # ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  children:
    web:
      hosts:
        FB-WEB-PROD: 192.168.1.28
    bdd:
      hosts:
        FB-DB-PROD: 192.168.1.29
test:
  hosts:
    FB-QUAL: 192.168.1.30
