---
# playbooks/test_common.yml
- name: Apply common rules
  hosts: all
  become: true  # Pour avoir les privilèges sudo
  gather_facts: true  # Pour collecter les informations sur les systèmes

  roles:
    - common


   
  